@FPL_Showcase_WD_HostAddress = https://localhost:7244

POST {{FPL_Showcase_WD_HostAddress}}/api/sync/players?force=true
Accept: application/json

###
GET {{FPL_Showcase_WD_HostAddress}}/api/fantasy/players
Accept: application/json

###