# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "Develop", "Release", "feat/*", "Bug/*" ]
  pull_request:
    branches: [ "main", "Develop", "Release", "feat/*", "Bug/*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

      - name: Voer unit tests uit en genereer rapport
        run: dotnet test --configuration Release --verbosity normal --results-directory "TestResults" --logger "trx;LogFileName=testresults.trx"

      - name: Upload test resultaten
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults/testresults.trx
